### PR TITLE
Remove jQuery

### PR DESCRIPTION
**Pull request by nicegamer7**
This PR removes the usage of jQuery from the script.

The first commit replaces the fetching of the English title, and the second commit saves the fetched title when it is received. The second commit is necessary because the previous solution (the `storeTranslated` function) no longer worked with the change from the first commit. The second commit also simplifies the code a bit, in my opinion.

### CODE REVIEW

**Comment by Animorphs** [comment]
Looking good, seems a cleaner solution than mine so far. Just a few things I can see at the moment that work in mine but will need to be touched up in yours:
- History: if you go to a users history it should display translations for each time the same show crops up. [Like this](https://i.imgur.com/MW8lEWe.png) 
- Errors: eliminate any extra errors in the console log. [Caught again in the history page](https://i.imgur.com/nOcqfMo.png)
- Alignment: you grab the outertext from the title-english, meaning it retains the \<p\> and adds extra whitespace, whilst I grab the innertext to make it fit nicer. [Example where lower part is good](https://i.imgur.com/lfs42v3.png)

Also I'm pretty inexperienced with JS (not a programmer/dev), but I assume the xhr part you added will wait for a response before saving the result?

**Comment by Animorphs** [comment]
Just updated my script with a bug fix, so please include that in your next commit too.
Additionally can you please put curly brackets on a newline to keep with my styling :)

**Comment by nicegamer7** [comment]
Okay, I've rebased my branch so that it includes the last fix you pushed.

I've also made sure to be consistent with your styling (sorry about that, I meant to change that before opening this PR but it was pretty late in my time zone and I was tired 😋). I also used `innerText` instead of `outerHTML`, and renamed the variables in that area to make more sense. And finally, I fixed the errors that showed up on the history page.

And yes, you're correct. The xhr part will only run after the web request is complete.

Oh, and on the subject of alignment, I found that the English title on tiles were not visually appealing (to me). And I found a way to make them look a little nicer. If you like it, let me know and I can include it here. https://imgur.com/rgcBAik

**Comment by Animorphs** [comment]
Looks good so far! Add in that centered tile view (definitely nicer than mine) and then I'll double check everything to make sure it's all good. Cheers for your help

**Comment by nicegamer7** [comment]
Alright, I pushed the alignment change and two more small changes. The first was just something I noticed on the history page, which is that the selectors were selecting some incorrect elements. And the second just updates the README to be accurate to the new behaviour.

Finally I just want to say thank you for making this script. I'm pretty new to anime and to MAL by extension, and this script has made using the site more enjoyable for me.

And by the way, I have a few more things in mind, so maybe some more PRs coming soon!

**Comment by Animorphs** [comment]
Thanks for doing all that, I fixed a few bugs (that were also in my version), tidied some stuff up and merged it with the master so should be good. Works much faster and cleaner now :)

And no worries for making it, I was in the same position as you and thought it was crazy it wasn't a part of the website already, so figured may as well make it.

Feel free to keep adding PRs as you need

**Pull request merged**
